### PR TITLE
Fix for XSS bug

### PR DESCRIPTION
**Pull request by ranjit-git**
There is stored xss present in issue-name and issue description .
Apply this fix to filter input and prevent xss 
https://huntr.dev/bounties/1625393956071-Volmarg/personal-management-system/
https://huntr.dev/bounties/1625394054448-Volmarg/personal-management-system/

If you want to see the report details then check your mail dwlodarczyk13@tlen.pl and you already have received the report magick  link

### CODE REVIEW

**Comment by Volmarg** [comment]
Hello,

Will try to take a look on it near weekend.

**Comment by Volmarg** [comment]
Accepted. You can send these to `personal.management.system.pms@gmail.com`

I will be using this email for this project related communication.

**Comment by JamieSlome** [comment]
@zidingz - just (cc) you here.

**Comment by zidingz** [comment]
Gotcha. personal.management.system.pms@gmail.com will receive an email within the hour. Thanks @Volmarg

**Comment by ranjit-git** [comment]
Hi, can you plz update the report status to valid .
First-one already validated but second-one not validated yet .

Thanks

**Pull request merged**
