### PR TITLE
Update composer hash in docker file

### PR DESCRIPTION
**Pull request by asurinsaka**
New composer hash cause the docker-compose to fail

### CODE REVIEW

**Comment by asurinsaka** [comment]
I could not get the docker-compose working:


encountered error like [this post](https://stackoverflow.com/questions/41209349/requirevendor-autoload-php-failed-to-open-stream) mentioned

**Comment by Volmarg** [comment]
Hello,
I'm not able to test the hash right now, probably will be able to at least make small check on weekend.

So with this - there is still some problem afterwards? Because I'm not sure how to understand Your second message.

**Comment by asurinsaka** [comment]
Ok, I was trying to solve the problem by myself. first it was trying to create var/cache/prod and did not have permission. I created the folder manually and have to set 777 to var folder so it can create anything it wants. I am not sure what user is in the docker. I haven't check yet. 

Now it is complaining:
```
Symfony\Component\Cache\Exception\CacheException:
APCu is not enabled.
```

**Comment by Volmarg** [comment]
Did You followed this: https://volmarg.github.io/docs/general/known-issues#php-apcu-extension ?

**Comment by Volmarg** [comment]
Ok, thanks, this solves the issue and now since I got docker installed on my own I see where the problem is, I will change that so the hash is no more ever needed.

**Pull request merged**
