### PR TITLE
Update Symfony to 4.3

### PR DESCRIPTION
**Pull request by j4nr6n**
This PR updates Symfony to 4.3 including the [November 2018 changes](https://symfony.com/doc/current/configuration/dot-env-changes.html) so it would be a good idea to copy `.env` to `.env.local` before pulling these changes.

### CODE REVIEW

**Comment by Volmarg** [comment]
Hmm. But the project already is 4.3.2 so there is no really need to update.

**Comment by Volmarg** [comment]
image

image

Besides I have bad experience with .env.local / dist. We have project on Symfony 4.2.x at work and all this .env didnt wored at all. Only the `.env` was being loaded so I had to write custom controller to load data depending on setted up `APP_ENV`.

So I'm not changing `.env` unless this was typically **4.2** problem.

**Comment by j4nr6n** [comment]
The November 2018 update includes changes to `bin/console` and `public/index.php` that loads a new file ([`config/bootstrap.php`](https://github.com/Volmarg/personal-management-system/pull/10/files#diff-2bad73d472db80e76e124fbfe9908964)). This update is one that had to be applied manually. If you don't do the steps listed [here](https://symfony.com/doc/current/configuration/dot-env-changes.html) the application won't load anything but `.env`.

It was already running 4.3.2 because [`composer.json`](https://github.com/Volmarg/personal-management-system/pull/10/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780) used `^4.0`. However dependencies changed since 4.0 `symfony/lts` was deprecated and is no longer used and Symfony's dependencies have changed slightly.

perhaps I made a mistake in saying "Update Symfony to 4.3". What I actually did was update the dependencies to match those of Symfony 4.3 by removing the deprecated ones and updating the requirement to "^4.3".

**Comment by Volmarg** [comment]
O, ok. You are playing with the project on updated version? If so - did You encountered any problems?

**Comment by j4nr6n** [comment]
Nope. I was able to run the server, build the assets and log into the application with fixture users. Browsed around a bit, etc. I wasn't able to run tests though, because, well... there aren't any yet.

**Comment by Volmarg** [comment]
Nice, but in my case this will have to wait. First i need to finish tagging mechanism - so this is definitely for later.

I'm not an TDD so I'm not working on tests.

**Comment by j4nr6n** [comment]
Thanks. I apologize for taking your time.

**Comment by Volmarg** [comment]
Nothing happened. I plan to do this later anyway. That's a useful info for me. I just can't allow myself to break the code and then search for bugs or update without checking it out.

**Pull request closed without merging**
